public enum AscendKitCommandCatalog {
    public static let usageLines: [String] = [
        "ascendkit version [--json]",
        "ascendkit workspace status --workspace PATH [--json]",
        "ascendkit workspace summary --workspace PATH [--json]",
        "ascendkit workspace hygiene --workspace PATH [--json]",
        "ascendkit workspace gitignore --workspace PATH [--fix] [--json]",
        "ascendkit workspace export-summary --workspace PATH --output FILE [--json]",
        "ascendkit workspace validate-handoff --workspace PATH [--export FILE] [--json]",
        "ascendkit workspace next-steps --workspace PATH [--json]",
        "ascendkit workspace audit --workspace PATH [--json]",
        "ascendkit workspace list [--root PATH] [--json]",
        "ascendkit intake inspect [--root PATH] [--project PATH] [--workspace PATH] [--release-id ID] [--save] [--json]",
        "ascendkit doctor release --workspace PATH [--json]",
        "ascendkit metadata init --workspace PATH [--locale en-US] [--json]",
        "ascendkit metadata import-fastlane --workspace PATH --source PATH [--json]",
        "ascendkit metadata status --workspace PATH [--json]",
        "ascendkit metadata lint --workspace PATH [--locale en-US] [--json]",
        "ascendkit metadata diff --workspace PATH [--json]",
        "ascendkit screenshots destinations --workspace PATH [--json]",
        "ascendkit screenshots plan --workspace PATH [--screens A,B] [--features A,B] [--platforms iOS,macOS] [--locales en-US] [--json]",
        "ascendkit screenshots copy init --workspace PATH [--locale en-US] [--output PATH] [--json]",
        "ascendkit screenshots copy refresh --workspace PATH [--locale en-US] [--copy PATH] [--output PATH] [--json]",
        "ascendkit screenshots copy lint --workspace PATH [--locale en-US] [--copy PATH] [--json]",
        "ascendkit screenshots capture-plan --workspace PATH [--scheme SCHEME] [--configuration Debug] [--destination DESTINATION] [--json]",
        "ascendkit screenshots capture --workspace PATH [--json]",
        "ascendkit screenshots workflow run --workspace PATH [--scheme SCHEME] [--configuration Debug] [--destination DESTINATION] [--mode storeReadyCopy|poster|deviceFrame|framedPoster] [--copy PATH] [--json]",
        "ascendkit screenshots workflow status --workspace PATH [--json]",
        "ascendkit screenshots readiness --workspace PATH [--source PATH] [--json]",
        "ascendkit screenshots import --workspace PATH --source PATH [--json]",
        "ascendkit screenshots import-fastlane --workspace PATH --source PATH [--locales en-US,zh-Hans] [--json]",
        "ascendkit screenshots compose --workspace PATH [--mode storeReadyCopy|poster|deviceFrame|framedPoster] [--copy PATH] [--json]",
        "ascendkit screenshots coverage --workspace PATH [--json]",
        "ascendkit screenshots upload-plan --workspace PATH [--display-type APP_IPHONE_67] [--replace-existing] [--json]",
        "ascendkit screenshots upload --workspace PATH [--replace-existing] --confirm-remote-mutation [--json]",
        "ascendkit screenshots upload-status --workspace PATH [--json]",
        "ascendkit asc auth save-profile --name NAME --issuer-id ID --key-id ID --private-key-provider env|file --private-key-ref REF [--json]",
        "ascendkit asc auth profiles [--json]",
        "ascendkit asc auth init --workspace PATH --issuer-id ID --key-id ID --private-key-provider env|file --private-key-ref REF [--json]",
        "ascendkit asc auth init --workspace PATH --profile NAME [--json]",
        "ascendkit asc auth check --workspace PATH [--json]",
        "ascendkit asc lookup plan --workspace PATH [--json]",
        "ascendkit asc lookup apps --workspace PATH [--json]",
        "ascendkit asc apps lookup --workspace PATH [--json]",
        "ascendkit asc builds observe --workspace PATH [--json]",
        "ascendkit asc builds list [--workspace PATH] [--json]",
        "ascendkit asc builds import --workspace PATH --id ID --version VERSION --build BUILD [--state STATE] [--json]",
        "ascendkit asc metadata import --workspace PATH --file PATH [--json]",
        "ascendkit asc metadata observe --workspace PATH [--json]",
        "ascendkit asc metadata plan --workspace PATH [--json]",
        "ascendkit asc metadata requests --workspace PATH [--json]",
        "ascendkit asc metadata apply --workspace PATH --confirm-remote-mutation [--json]",
        "ascendkit asc metadata status --workspace PATH [--json]",
        "ascendkit asc pricing set-free --workspace PATH [--app-id ID] [--base-territory USA] [--confirm-remote-mutation] [--json]",
        "ascendkit asc privacy set-not-collected --workspace PATH [--app-id ID] --confirm-remote-mutation [--json]",
        "ascendkit asc privacy status --workspace PATH [--json]",
        "ascendkit asc privacy confirm-manual --workspace PATH --data-not-collected [--json]",
        "ascendkit submit readiness --workspace PATH [--json]",
        "ascendkit submit prepare --workspace PATH [--json]",
        "ascendkit submit review-plan --workspace PATH [--json]",
        "ascendkit submit handoff --workspace PATH [--json]",
        "ascendkit submit execute --workspace PATH --confirm-remote-submission [--json]   # boundary-disabled; records non-execution",
        "ascendkit submit review-info init --workspace PATH [--json]",
        "ascendkit submit review-info set --workspace PATH --first-name NAME --last-name NAME --email EMAIL --phone PHONE [--notes TEXT] [--requires-login true|false] [--credential-ref ENV_VAR] [--access-instructions TEXT] [--json]",
        "ascendkit iap template init --workspace PATH [--json]",
        "ascendkit iap validate --workspace PATH [--json]"
    ]

    public static var helpText: String {
        (["AscendKit", "", "Usage:"] + usageLines.map { "  \($0)" }).joined(separator: "\n")
    }
}
